2021-12-03 13:39:51,262 INFO    MainThread:7634 [wandb_setup.py:_flush():69] setting env: {'project': 'exercise_10', 'run_group': 'dev'}
2021-12-03 13:39:51,262 INFO    MainThread:7634 [wandb_setup.py:_flush():69] setting login settings: {}
2021-12-03 13:39:51,263 INFO    MainThread:7634 [wandb_init.py:_log_setup():334] Logging user logs to /Users/ozgecaylioglu/Desktop/GitHub_Projects/udacity_repo/Project2/Lesson5_Exercise10/random_forest/wandb/run-20211203_133951-7rtryahi/logs/debug.log
2021-12-03 13:39:51,263 INFO    MainThread:7634 [wandb_init.py:_log_setup():335] Logging internal logs to /Users/ozgecaylioglu/Desktop/GitHub_Projects/udacity_repo/Project2/Lesson5_Exercise10/random_forest/wandb/run-20211203_133951-7rtryahi/logs/debug-internal.log
2021-12-03 13:39:51,264 INFO    MainThread:7634 [wandb_init.py:init():367] calling init triggers
2021-12-03 13:39:51,264 INFO    MainThread:7634 [wandb_init.py:init():372] wandb.init called with sweep_config: {}
config: {}
2021-12-03 13:39:51,264 INFO    MainThread:7634 [wandb_init.py:init():416] starting backend
2021-12-03 13:39:51,264 INFO    MainThread:7634 [backend.py:_multiprocessing_setup():69] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2021-12-03 13:39:51,376 INFO    MainThread:7634 [backend.py:ensure_launched():123] starting backend process...
2021-12-03 13:39:51,390 INFO    MainThread:7634 [backend.py:ensure_launched():127] started backend process with pid: 7644
2021-12-03 13:39:51,393 INFO    MainThread:7634 [wandb_init.py:init():421] backend started and connected
2021-12-03 13:39:51,402 INFO    MainThread:7634 [wandb_init.py:init():461] updated telemetry
2021-12-03 13:39:51,403 INFO    MainThread:7634 [wandb_init.py:init():480] communicating current version
2021-12-03 13:39:52,691 INFO    MainThread:7634 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.12.7 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-12-03 13:39:52,692 INFO    MainThread:7634 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-12-03 13:39:53,195 INFO    MainThread:7634 [wandb_init.py:init():518] starting run threads in backend
2021-12-03 13:39:53,265 INFO    MainThread:7634 [wandb_run.py:_console_start():1476] atexit reg
2021-12-03 13:39:53,266 INFO    MainThread:7634 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.REDIRECT
2021-12-03 13:39:53,267 INFO    MainThread:7634 [wandb_run.py:_redirect():1344] Redirecting console.
2021-12-03 13:39:53,267 INFO    MainThread:7634 [redirect.py:install():213] install start
2021-12-03 13:39:53,268 INFO    MainThread:7634 [redirect.py:install():228] install stop
2021-12-03 13:39:53,268 INFO    MainThread:7634 [redirect.py:install():213] install start
2021-12-03 13:39:53,269 INFO    MainThread:7634 [redirect.py:install():228] install stop
2021-12-03 13:39:53,269 INFO    MainThread:7634 [wandb_run.py:_redirect():1390] Redirects installed.
2021-12-03 13:39:53,269 INFO    MainThread:7634 [wandb_init.py:init():542] run started, returning control to user process
2021-12-03 13:39:56,109 INFO    MainThread:7634 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 1
2021-12-03 13:39:56,110 INFO    MainThread:7634 [wandb_run.py:_restore():1418] restore
2021-12-03 13:39:56,111 INFO    MainThread:7634 [redirect.py:uninstall():232] uninstall start
2021-12-03 13:39:56,111 INFO    MainThread:7634 [redirect.py:_stop():287] _stop: stdout
2021-12-03 13:39:56,111 INFO    MainThread:7634 [redirect.py:_stop():293] _stop closed: stdout
2021-12-03 13:39:56,111 INFO    stdout    :7634 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2021-12-03 13:39:56,112 INFO    stdout    :7634 [redirect.py:_pipe_relay():145] relay done done: stdout
2021-12-03 13:39:56,112 INFO    MainThread:7634 [redirect.py:_stop():299] _stop joined: stdout
2021-12-03 13:39:56,112 INFO    MainThread:7634 [redirect.py:_stop():301] _stop rd closed: stdout
2021-12-03 13:39:56,112 INFO    MainThread:7634 [redirect.py:uninstall():236] uninstall done
2021-12-03 13:39:56,112 INFO    MainThread:7634 [redirect.py:uninstall():232] uninstall start
2021-12-03 13:39:56,112 INFO    MainThread:7634 [redirect.py:_stop():287] _stop: stderr
2021-12-03 13:39:56,112 INFO    stderr    :7634 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2021-12-03 13:39:56,113 INFO    stderr    :7634 [redirect.py:_pipe_relay():145] relay done done: stderr
2021-12-03 13:39:56,113 INFO    MainThread:7634 [redirect.py:_stop():293] _stop closed: stderr
2021-12-03 13:39:56,113 INFO    MainThread:7634 [redirect.py:_stop():299] _stop joined: stderr
2021-12-03 13:39:56,113 INFO    MainThread:7634 [redirect.py:_stop():301] _stop rd closed: stderr
2021-12-03 13:39:56,113 INFO    MainThread:7634 [redirect.py:uninstall():236] uninstall done
2021-12-03 13:39:56,631 INFO    MainThread:7634 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 1026
}

2021-12-03 13:39:58,636 INFO    MainThread:7634 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 1026
  total_bytes: 2565
}

2021-12-03 13:40:00,646 INFO    MainThread:7634 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 2565
  total_bytes: 2565
}

2021-12-03 13:40:01,828 INFO    MainThread:7634 [wandb_run.py:_show_files():1790] logging synced files
