[1mcollecting 1 item                                                              [0m[1mcollected 1 item                                                               [0m

test_data.py::test_kolmogorov_smirnov [31mFAILED[0m

=================================== FAILURES ===================================
[31m[1m___________________________ test_kolmogorov_smirnov ____________________________[0m

data = (       Unnamed: 0  ...                                       text_feature
0           27919  ...                     ...ll on to Forrest Trance 
12592       34043  ...                            Lost Lands 2019 

[12593 rows x 20 columns])

    def test_kolmogorov_smirnov(data):
    
        sample1, sample2 = data
    
        numerical_columns = [
            "danceability",
            "energy",
            "loudness",
            "speechiness",
            "acousticness",
            "instrumentalness",
            "liveness",
            "valence",
            "tempo",
            "duration_ms"
        ]
    
        # Let's decide the Type I error probability (related to the False Positive Rate)
        alpha = 0.05
        # Bonferroni correction for multiple hypothesis testing
        # (see my blog post on this topic to see where this comes from:
        # https://towardsdatascience.com/precision-and-recall-trade-off-and-multiple-hypothesis-testing-family-wise-error-rate-vs-false-71a85057ca2b)
        alpha_prime = 1 - (1 - alpha)**(1 / len(numerical_columns))
    
        for col in numerical_columns:
    
            # Use the 2-sample KS test (scipy.stats.ks_2sample) on the column
            # col
>           ts, p_value = scipy.stats.ks_2sample(sample1[col], sample2[col])
[1m[31mE           AttributeError: module 'scipy.stats' has no attribute 'ks_2sample'[0m

[1m[31mtest_data.py[0m:51: AttributeError
[33m=============================== warnings summary ===============================[0m
../../../../../../../opt/anaconda3/envs/mlflow-7398531e5288219e428182dc4d6601ae57991d39/lib/python3.9/site-packages/wandb/vendor/watchdog/utils/bricks.py:175
  /opt/anaconda3/envs/mlflow-7398531e5288219e428182dc4d6601ae57991d39/lib/python3.9/site-packages/wandb/vendor/watchdog/utils/bricks.py:175: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
    class OrderedSet(collections.MutableSet):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED test_data.py::test_kolmogorov_smirnov - AttributeError: module 'scipy....
[31m======================== [31m[1m1 failed[0m, [33m1 warning[0m[31m in 35.79s[0m[31m =========================[0m
